language: node_js
sudo: false
notifications:
  email: false
node_js:
  - "10" # latest stable
  - "8" # LTS
before_script:
  - npm prune
after_success:
  - npm run coverage
  - npm run semantic-release
branches:
except:
  - /^v\d+\.\d+\.\d+$/
